### ISSUE TITLE
Swifty downloading over and over again

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#122] opened 2016-01-27 18:30 UTC
Swifty: 2.1.2.2

We're encountering the problem, that swifty is downloading the same changes over and over again.

Swifty.log: http://pastebin.com/wukP4FKh

**Comment by bux578** [comment] 2016-01-27 18:31
Short clip of the problem: https://www.youtube.com/watch?v=P12zm7hw2eM

**Comment by headswe** [comment] 2016-02-06 19:24
Did you do something to solve this other then deleting the pbos?

**Comment by bux578** [comment] 2016-02-06 19:45
No, I did not.

**Comment by gfolkersma** [comment] 2016-02-10 20:29
I have the same problem, and the files are missing in the addons destination. Is there a fix for this?

**Comment by headswe** [comment] 2016-02-11 13:51
Can you send me the pbos that causes this?

**Comment by gfolkersma** [comment] 2016-02-11 21:18
I would, but it doesn't seem to be caused by the same addons each time. I even made a separate repo with the offending files that are now stuck, and that one works fine. 
Note that the "processing changes... 1%"  takes 10 min (22GB repo), even for 21MB of "modified files".

Feel free testing the (big!) repo at: http://thuis.folkersma.org/A3/SwiftyRepo/

**Comment by headswe** [comment] 2016-02-13 12:51
Be sure you using the latest version from website since there was the internal updater broke on .9 version.

A few logs when this occur be great too.

**Comment by gfolkersma** [comment] 2016-02-13 14:00
I'm on 2.1.2.2, should be the most recent one right? 

Here is the log of one cycle: Starting Swifty, waiting for the processing, downloading the modifications, and waiting for processing again.  (And I could do it again, and again).
http://pastebin.com/AacNmTP3

**Comment by gfolkersma** [comment] 2016-02-15 21:34
It seems to be fixed by re-building the repo (and some addons were added). 
Another bug (or feature): The repo folder is not cleaned before building a new one in it, making it very messy.

**Comment by headswe** [comment] 2016-02-16 12:58
I'm glad a rebuild solved it.

**Closed** 2016-03-11 13:42 UTC
Labels: bug
