### ISSUE TITLE
Bitdefender classifies Swifty as a malware

### ISSUE THREAD

**Issue by Janne36** [headswe/Swifty#212] opened 2017-09-24 15:24 UTC
I am unable to install Swifty because it gets classified as malware by Bitdefender thread defence. Not even whitelisting setup.exe for Bitdefender helped. Not sure if error is in the Bitdefenders or yours end but I think this is still something that should be looked at. I was able to use previous version just fine, this happened when I tried to install new version. 

Attached picture and error log. 

[SquirrelSetup.log](https://github.com/headswe/Swifty/files/1327419/SquirrelSetup.log)
![error](https://user-images.githubusercontent.com/17467886/30783962-ec4a18e0-a154-11e7-8ad6-81cec11fc697.jpg)

**Comment by Sniperhid** [comment] 2017-09-24 15:59
Duplicate of #135 - https://github.com/headswe/Swifty/issues/135
See last response on the above.

**Closed by Sniperhid** 2017-09-24 15:59 UTC
